#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

// Noto Sans CJK SC at 20px, GB2312 plus ASCII, generated by
// tools/gencjkfont.py. See that script for the licence, the source of the
// typeface, and why the charset stops where it does.
//
// ⚠️ This is the ONLY font in the firmware that can draw a Chinese character.
// Every other face here is Montserrat, which covers 0x20-0x7F -- so a label
// that might hold a name from the phone must use this one or draw nothing.
//
// It carries ASCII too, deliberately: LVGL cannot switch faces inside a
// label, so a mixed name like "Alex 张" would otherwise lose half of itself.
// That does NOT make it a general-purpose font -- it is 750KB, and Montserrat
// stays the face for everything that can only ever be ASCII.
//
// 20px rather than the 24px its neighbour uses: a hanzi fills its box where a
// Latin capital fills about two thirds of the height, so the two sizes look
// alike beside each other, and 20px is where the strokes still separate at
// 2 bits of coverage.
extern const lv_font_t pegasus_font_cjk_20;

#ifdef __cplusplus
}
#endif
