#pragma once

#include <lvgl.h>

// A Montserrat face carrying only digits, '-' and '.', generated by
// tools/gennumfont.py from the same TTF LVGL builds its own fonts from.
//
// It exists because LVGL's built-in Montserrat stops at 48pt, and the distance
// to the next turn is the one number on this panel that has to be read without
// looking straight at it. Its digits are 64px tall against the 34px the 48pt
// face manages.
//
// Restricted to the characters FormatTbtDistance can actually produce --
// "157", "1.2", and the "--" shown when a turn arrives without a distance.
// A full face at this size would spend tens of kilobytes of flash on glyphs
// nothing here can render.
//
// Defined in a .c file, so C linkage.
#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t pegasus_font_num_88;

// The second page's figures, in two sizes because its two columns are two
// widths. Emboldened: Montserrat Medium is the only weight LVGL vendors and a
// thin face is the first thing a rider loses in bright sun, so the generator
// draws these with an outline stroke rather than adding a second TTF here.
//
// Both sizes are measured, not chosen. The widest string either can hold is
// "99.9", and it has to fit the column minus two 4px insets:
//
//   live column     150 wide, 142 usable   58 gives 137   (60 gives 141)
//   average column   90 wide,  82 usable   30 gives  80   (32 gives  83)
//
// The live figures are what a rider reads at speed and get the wide column;
// the averages are read at a stop. That is the whole reason the columns are
// unequal, and the reason the averages are small.
extern const lv_font_t pegasus_font_num_58b;
extern const lv_font_t pegasus_font_num_30b;

#ifdef __cplusplus
}
#endif
