#pragma once

#include <lvgl.h>

// A Montserrat face carrying only digits, '-' and '.', generated by
// tools/gennumfont.py from the same TTF LVGL builds its own fonts from.
//
// It exists because LVGL's built-in Montserrat stops at 48pt, and the distance
// to the next turn is the one number on this panel that has to be read without
// looking straight at it. Its digits are 64px tall against the 34px the 48pt
// face manages.
//
// Restricted to the characters FormatTbtDistance can actually produce --
// "157", "1.2", and the "--" shown when a turn arrives without a distance.
// A full face at this size would spend tens of kilobytes of flash on glyphs
// nothing here can render.
//
// Defined in a .c file, so C linkage.
#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t pegasus_font_num_88;

// The second page's live speed and heart rate, at 1.2x the 48pt face: 41px
// digits against its 34. Generated for the same reason as the 88 above --
// LVGL's Montserrat stops at 48 -- and restricted to the same characters,
// which is every one those two readouts can produce including the "--" they
// show before a fix or a strap.
//
// It costs 12.6KB. A full ASCII face at this size would be nearer 130.
extern const lv_font_t pegasus_font_num_58;

#ifdef __cplusplus
}
#endif
