#!/usr/bin/env python3
"""Generate an LVGL font holding only the characters the distance readout uses.

LVGL's built-in Montserrat stops at 48pt, and the turn distance is the one
number on this panel that has to be read without looking straight at it. A
bigger face therefore has to be generated, and LVGL's own converter is a Node
tool that is not installed here -- so this renders the glyphs with Pillow and
emits the same C structures the built-in fonts use.

Only 0x2D..0x39 is covered: '-', '.', '/' and the ten digits. That is every
character FormatTbtDistance can produce, including the "--" it shows when the
phone names a turn without saying how far away it is. A full face at this size
would cost tens of kilobytes of flash for glyphs nothing here can render.

The source is the same Montserrat-Medium.ttf LVGL builds its own fonts from,
taken from the vendored library so the big digits and the small unit beside
them are the same typeface rather than merely similar ones.

    python tools/gennumfont.py <out.c> <size_px> [stroke_px]

`stroke_px` emboldens. Only one weight of Montserrat is vendored with LVGL --
Medium -- and a thin face is what a rider loses first in bright sun or at a
glance. Rather than add a second TTF to the repo, the glyphs are drawn with an
outline stroke, which thickens them from the same outlines. It costs width and
height: each glyph grows by twice the stroke in both directions, and the
advance and the line box grow with it.
"""
import sys

from PIL import Image, ImageDraw, ImageFont

TTF = ".pio/libdeps/esp32s3/lvgl/scripts/built_in_font/Montserrat-Medium.ttf"

# '-' through '9': hyphen, full stop, solidus, and the digits. Contiguous, so
# the character map is the single cheapest kind LVGL has.
FIRST = 0x2D
LAST = 0x39
CHARS = [chr(c) for c in range(FIRST, LAST + 1)]

PAD = 8  # canvas margin, so no glyph is clipped before it is measured


# Inside the range but never rendered. The solidus is the only glyph here that
# descends below the baseline, and keeping it would push the line box 18px
# taller for a character no distance string can contain. The codepoint stays so
# the character map remains one contiguous range, the cheapest kind LVGL has.
BLANK = "/"


def render(font, ch, ascent, descent, stroke=0):
    """One glyph as (coverage bytes, box_w, box_h, ofs_x, ofs_y, adv_w)."""
    if ch in BLANK:
        return b"", 0, 0, 0, 0, 0
    height = ascent + descent + 2 * PAD + 2 * stroke
    width = int(font.getlength(ch)) + 4 * PAD + 2 * stroke
    img = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(img)
    # "ls" anchors at the left edge on the BASELINE, which is the origin LVGL
    # measures its offsets from too.
    #
    # The pen starts `stroke` to the right of the padding, because the outline
    # grows outwards in every direction: without the shift the ink would begin
    # left of the origin and every glyph would carry a negative ofs_x.
    draw.text((PAD + stroke, PAD + ascent), ch, font=font, fill=255, anchor="ls",
              stroke_width=stroke, stroke_fill=255)

    box = img.getbbox()
    # The advance has to grow by the stroke on both sides, or an emboldened
    # glyph overlaps the one after it. getlength() knows nothing about it.
    adv_w = int(round((font.getlength(ch) + 2 * stroke) * 16))  # 1/16 px
    if box is None:  # a blank glyph, e.g. a space
        return b"", 0, 0, 0, 0, adv_w

    x0, y0, x1, y1 = box
    crop = img.crop(box)
    # ofs_y is the baseline-to-box-bottom distance, positive upwards. A digit
    # sitting on the baseline gives 0; a comma hanging below gives a negative.
    ofs_y = (PAD + ascent) - y1
    return crop.tobytes(), x1 - x0, y1 - y0, x0 - PAD, ofs_y, adv_w


def main():
    out_c, size = sys.argv[1], int(sys.argv[2])
    stroke = int(sys.argv[3]) if len(sys.argv) > 3 else 0
    font = ImageFont.truetype(TTF, size)
    ascent, descent = font.getmetrics()

    glyphs = [render(font, ch, ascent, descent, stroke) for ch in CHARS]

    # The weight is part of the name: a bold 55 and a regular 55 are different
    # faces and must not answer to the same symbol.
    name = f"pegasus_font_num_{size}" + ("b" if stroke else "")
    blob = bytearray()
    dscs = []
    for data, w, h, ox, oy, adv in glyphs:
        dscs.append((len(blob), adv, w, h, ox, oy))
        blob += data

    with open(out_c, "w") as f:
        f.write("// GENERATED by tools/gennumfont.py -- do not edit by hand.\n")
        f.write(f"// Regenerate: python tools/gennumfont.py {out_c} {size} {stroke}\n")
        f.write("//\n")
        f.write("// Montserrat Medium, digits and separators only, 8 bits of coverage per\n")
        f.write("// pixel. LVGL's built-in faces stop at 48pt and the turn distance needs\n")
        f.write("// to be read without looking straight at it; its own converter is a Node\n")
        f.write("// tool that is not installed here, so the glyphs are rendered with Pillow\n")
        f.write("// and emitted in the same structures the built-in fonts use.\n\n")
        f.write('#include "lvgl.h"\n\n')

        f.write("static const uint8_t glyph_bitmap[] = {\n")
        for i in range(0, len(blob), 16):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) + ",\n")
        f.write("};\n\n")

        f.write("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n")
        f.write("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0,"
                " .ofs_x = 0, .ofs_y = 0}, /* id 0 is reserved */\n")
        for idx, adv, w, h, ox, oy in dscs:
            f.write(f"    {{.bitmap_index = {idx}, .adv_w = {adv}, .box_w = {w},"
                    f" .box_h = {h}, .ofs_x = {ox}, .ofs_y = {oy}}},\n")
        f.write("};\n\n")

        f.write("static const lv_font_fmt_txt_cmap_t cmaps[] = {\n")
        f.write("    {\n")
        f.write(f"        .range_start = {FIRST}, .range_length = {len(CHARS)},"
                " .glyph_id_start = 1,\n")
        f.write("        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,\n")
        f.write("        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY\n")
        f.write("    }\n};\n\n")

        f.write("static lv_font_fmt_txt_glyph_cache_t cache;\n")
        f.write("static const lv_font_fmt_txt_dsc_t font_dsc = {\n")
        f.write("    .glyph_bitmap = glyph_bitmap,\n")
        f.write("    .glyph_dsc = glyph_dsc,\n")
        f.write("    .cmaps = cmaps,\n")
        # No kerning table. It only matters between letter pairs, and these are
        # digits: a fixed advance is what keeps a counting-down number from
        # twitching sideways as its digits change.
        f.write("    .kern_dsc = NULL,\n")
        f.write("    .kern_scale = 0,\n")
        f.write("    .cmap_num = 1,\n")
        f.write("    .bpp = 8,\n")
        f.write("    .kern_classes = 0,\n")
        f.write("    .bitmap_format = 0,\n")
        f.write("    .cache = &cache\n};\n\n")

        f.write(f"const lv_font_t {name} = {{\n")
        f.write("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n")
        f.write("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n")
        # The font's own ascent and descent describe a face with letters in
        # it. This one has digits, a hyphen and a full stop: nothing descends
        # below the baseline and nothing reaches an ascender. Using the real
        # metrics would reserve ~19px of empty line box on a tile that is
        # fighting for every pixel, so the line is measured from the glyphs
        # that actually exist.
        top = max((h + oy) for _, _, w, h, _, oy in dscs if h)
        bottom = min((oy) for _, _, w, h, _, oy in dscs if h)
        f.write(f"    .line_height = {top - min(0, bottom)},\n")
        f.write(f"    .base_line = {max(0, -bottom)},\n")
        f.write("    .subpx = LV_FONT_SUBPX_NONE,\n")
        f.write(f"    .underline_position = {-max(1, size // 12)},\n")
        f.write(f"    .underline_thickness = {max(1, size // 24)},\n")
        f.write("    .dsc = &font_dsc\n};\n")

    digit_h = max(h for _, _, _, h, _, _ in [(0, 0, 0, g[2], 0, 0) for g in glyphs])
    print(f"{name}: {len(CHARS)} glyphs, {len(blob) / 1024:.1f} KB")
    top = max((h + oy) for _, _, w, h, _, oy in dscs if h)
    bottom = min((oy) for _, _, w, h, _, oy in dscs if h)
    print(f"line_height={top - min(0, bottom)} base_line={max(0, -bottom)} "
          f"digit_height={digit_h}")


if __name__ == "__main__":
    main()
