#!/usr/bin/env python3
"""Turn an image into the boot splash the panel shows while it starts up.

LVGL can decode a PNG at runtime, and doing that here would be the wrong trade:
the splash has to appear before anything else, decoding costs a 150KB buffer
and a second of CPU at the exact moment the board has neither to spare, and a
decoder failure would leave a blank screen with nothing to report it. So the
image is converted here, once, into the pixels the panel wants -- the firmware
does nothing at boot but hand a pointer to the display driver.

Output is LV_IMG_CF_TRUE_COLOR: an array of lv_color_t, which at
LV_COLOR_DEPTH 16 is RGB565, little-endian, one uint16 per pixel. That matches
LV_COLOR_16_SWAP 0 in include/lv_conf.h. If the splash ever comes out with red
and blue exchanged, those two settings have drifted apart and this is the file
that has to follow.

The image is scaled to COVER 240x320 and centre-cropped, never letterboxed:
bars down the sides of a boot screen read as a broken image rather than as a
deliberate frame.

    python tools/gensplash.py <in.png|jpg> <out.c>
"""
import sys

from PIL import Image

W = 240
H = 320
NAME = "pegasus_splash"


def cover(img):
    """Scale to fill W x H, then crop the overflow off the centre."""
    scale = max(W / img.width, H / img.height)
    resized = img.resize((max(W, round(img.width * scale)), max(H, round(img.height * scale))),
                         Image.LANCZOS)
    left = (resized.width - W) // 2
    top = (resized.height - H) // 2
    return resized.crop((left, top, left + W, top + H))


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1

    img = cover(Image.open(sys.argv[1]).convert("RGB"))

    blob = bytearray()
    for y in range(H):
        for x in range(W):
            r, g, b = img.getpixel((x, y))
            # 8 bits down to 5/6/5. Truncation rather than dithering: the
            # banding it avoids is invisible for two seconds, and dithering a
            # flat sky produces a texture that looks like screen noise.
            pixel = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            blob.append(pixel & 0xFF)   # little-endian, as lv_color_t is stored
            blob.append(pixel >> 8)

    with open(sys.argv[2], "w") as f:
        f.write("// GENERATED by tools/gensplash.py -- do not edit by hand.\n")
        f.write(f"// Regenerate: python tools/gensplash.py <image> {sys.argv[2]}\n")
        f.write("//\n")
        f.write(f"// {W}x{H} RGB565, the panel's own format, so the boot path does no\n")
        f.write("// decoding at all -- see the tool for why that matters at this moment.\n\n")
        f.write('#include "lvgl.h"\n\n')
        f.write("static const uint8_t splash_map[] = {\n")
        for i in range(0, len(blob), 16):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write(f"const lv_img_dsc_t {NAME} = {{\n")
        f.write("    .header = {.cf = LV_IMG_CF_TRUE_COLOR, .always_zero = 0, .reserved = 0,\n")
        f.write(f"               .w = {W}, .h = {H}}},\n")
        f.write("    .data_size = sizeof(splash_map),\n")
        f.write("    .data = splash_map,\n")
        f.write("};\n")

    print(f"{NAME}: {W}x{H}, {len(blob) / 1024:.1f} KB of flash")
    return 0


if __name__ == "__main__":
    sys.exit(main())
